// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/scalewise/BrowseExperts.tsx": () => import("../components/mockups/scalewise/BrowseExperts.tsx"),
  "./components/mockups/scalewise/ExpertProfile.tsx": () => import("../components/mockups/scalewise/ExpertProfile.tsx"),
  "./components/mockups/scalewise/Homepage.tsx": () => import("../components/mockups/scalewise/Homepage.tsx")
};
