// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/growpia/BrowseExperts.tsx": () => import("../components/mockups/growpia/BrowseExperts.tsx"),
  "./components/mockups/growpia/ExpertProfile.tsx": () => import("../components/mockups/growpia/ExpertProfile.tsx"),
  "./components/mockups/growpia/Homepage.tsx": () => import("../components/mockups/growpia/Homepage.tsx"),
  "./components/mockups/growpia/HomepageV2.tsx": () => import("../components/mockups/growpia/HomepageV2.tsx")
};
